version: "2.3"
services:

  vscode:
    image: braintwister/ubuntu-20.04-cuda-devel-11.0-gcc-9-clang-9-vscode-1.49.1:0.4
    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - home:/home/${USER_NAME}
      - ${GIT_DIR}:/home/${USER_NAME}/git
      - ${DATA_DIR}:/home/${USER_NAME}/data:ro
    environment:
      - DISPLAY
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USER_NAME=${USER_NAME}
      - GROUP_NAME=${GROUP_NAME}
    network_mode: host
    ports:
      - 6006:6006
    privileged: true

volumes:
  home:

