version: "2.3"
services:

  vscode:
    image: braintwister/cuda-devel-11.4.2-gcc-9-clang-9-vscode-1.60.2:0.5
    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - home:/home/${USER_NAME}
      - ${GIT_DIR}:/home/${USER_NAME}/git
      - ${DATA_DIR}:/home/${USER_NAME}/data:ro
    environment:
      - DISPLAY
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USER_NAME=${USER_NAME}
      - GROUP_NAME=${GROUP_NAME}
    network_mode: host
    privileged: true

volumes:
  home:

